# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cron.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncron.proto\"\x1c\n\rReturnMessage\x12\x0b\n\x03msn\x18\x01 \x01(\t\"3\n\x15GetWeatherDataRequest\x12\x0c\n\x04temp\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\"L\n\x13GetCoinsDataRequest\x12\r\n\x05\x64olar\x18\x01 \x01(\t\x12\x0c\n\x04\x65uro\x18\x02 \x01(\t\x12\n\n\x02uf\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\t2v\n\x04\x44\x61ta\x12\x38\n\x0eGetWeatherData\x12\x16.GetWeatherDataRequest\x1a\x0e.ReturnMessage\x12\x34\n\x0cGetCoinsData\x12\x14.GetCoinsDataRequest\x1a\x0e.ReturnMessageb\x06proto3')



_RETURNMESSAGE = DESCRIPTOR.message_types_by_name['ReturnMessage']
_GETWEATHERDATAREQUEST = DESCRIPTOR.message_types_by_name['GetWeatherDataRequest']
_GETCOINSDATAREQUEST = DESCRIPTOR.message_types_by_name['GetCoinsDataRequest']
ReturnMessage = _reflection.GeneratedProtocolMessageType('ReturnMessage', (_message.Message,), {
  'DESCRIPTOR' : _RETURNMESSAGE,
  '__module__' : 'cron_pb2'
  # @@protoc_insertion_point(class_scope:ReturnMessage)
  })
_sym_db.RegisterMessage(ReturnMessage)

GetWeatherDataRequest = _reflection.GeneratedProtocolMessageType('GetWeatherDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETWEATHERDATAREQUEST,
  '__module__' : 'cron_pb2'
  # @@protoc_insertion_point(class_scope:GetWeatherDataRequest)
  })
_sym_db.RegisterMessage(GetWeatherDataRequest)

GetCoinsDataRequest = _reflection.GeneratedProtocolMessageType('GetCoinsDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCOINSDATAREQUEST,
  '__module__' : 'cron_pb2'
  # @@protoc_insertion_point(class_scope:GetCoinsDataRequest)
  })
_sym_db.RegisterMessage(GetCoinsDataRequest)

_DATA = DESCRIPTOR.services_by_name['Data']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RETURNMESSAGE._serialized_start=14
  _RETURNMESSAGE._serialized_end=42
  _GETWEATHERDATAREQUEST._serialized_start=44
  _GETWEATHERDATAREQUEST._serialized_end=95
  _GETCOINSDATAREQUEST._serialized_start=97
  _GETCOINSDATAREQUEST._serialized_end=173
  _DATA._serialized_start=175
  _DATA._serialized_end=293
# @@protoc_insertion_point(module_scope)
