# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cron.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncron.proto\"\x1c\n\rReturnMessage\x12\x0b\n\x03msn\x18\x01 \x01(\t\"3\n\x15GetWeatherDataRequest\x12\x0c\n\x04temp\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\"L\n\x13GetCoinsDataRequest\x12\r\n\x05\x64olar\x18\x01 \x01(\t\x12\x0c\n\x04\x65uro\x18\x02 \x01(\t\x12\n\n\x02uf\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\t2z\n\x04\x44\x61ta\x12:\n\x0eGetWeatherData\x12\x16.GetWeatherDataRequest\x1a\x0e.ReturnMessage\"\x00\x12\x36\n\x0cGetCoinsData\x12\x14.GetCoinsDataRequest\x1a\x0e.ReturnMessage\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cron_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RETURNMESSAGE._serialized_start=14
  _RETURNMESSAGE._serialized_end=42
  _GETWEATHERDATAREQUEST._serialized_start=44
  _GETWEATHERDATAREQUEST._serialized_end=95
  _GETCOINSDATAREQUEST._serialized_start=97
  _GETCOINSDATAREQUEST._serialized_end=173
  _DATA._serialized_start=175
  _DATA._serialized_end=297
# @@protoc_insertion_point(module_scope)
