# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cron_pb2 as cron__pb2


class DataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWeatherData = channel.unary_unary(
                '/Data/GetWeatherData',
                request_serializer=cron__pb2.GetWeatherDataRequest.SerializeToString,
                response_deserializer=cron__pb2.ReturnMessage.FromString,
                )
        self.GetCoinsData = channel.unary_unary(
                '/Data/GetCoinsData',
                request_serializer=cron__pb2.GetCoinsDataRequest.SerializeToString,
                response_deserializer=cron__pb2.ReturnMessage.FromString,
                )


class DataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetWeatherData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCoinsData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWeatherData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeatherData,
                    request_deserializer=cron__pb2.GetWeatherDataRequest.FromString,
                    response_serializer=cron__pb2.ReturnMessage.SerializeToString,
            ),
            'GetCoinsData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoinsData,
                    request_deserializer=cron__pb2.GetCoinsDataRequest.FromString,
                    response_serializer=cron__pb2.ReturnMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Data', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Data(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetWeatherData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Data/GetWeatherData',
            cron__pb2.GetWeatherDataRequest.SerializeToString,
            cron__pb2.ReturnMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCoinsData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Data/GetCoinsData',
            cron__pb2.GetCoinsDataRequest.SerializeToString,
            cron__pb2.ReturnMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
