apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cronjob
  name: cronjob
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cronjob
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cronjob
    spec:
      containers:
        - image: lucasalmonacid/flask_mdb_cronjob
          name: python-cronjob
          ports:
            - containerPort: 8060
          resources: {}
      restartPolicy: Always
status: {}
