name: Build & publish images
on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./API/Dockerfile
            image: flask_mdb_api
            context: ./API/
          - dockerfile: Dockerfile
            image: ./backend/flask_mdb_backend
            context: ./backend/
          - dockerfile: Dockerfile
            image: ./cronjob/flask_mdb_cronjob
            context: ./cronjob/
          - dockerfile: Dockerfile
            image: ./frontend/flask_mdb_frontend
            context: ./frontend/
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest
